import json
import time

# Manual repos from the stars list that couldn't be fetched via API
manual_repos = [
    {
        "repo": "deepseek-ai/DeepSeek-R1",
        "full_name": "deepseek-ai/DeepSeek-R1",
        "name": "DeepSeek-R1",
        "owner": "deepseek-ai",
        "description": "Advanced reasoning model from DeepSeek AI",
        "html_url": "https://github.com/deepseek-ai/DeepSeek-R1",
        "stargazers_count": 91848,
        "forks_count": 11773,
        "open_issues_count": 0,
        "language": "Python",
        "license": None,
        "topics": ["ai", "llm", "reasoning"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "deepseek-ai/DeepSeek-V3",
        "full_name": "deepseek-ai/DeepSeek-V3",
        "name": "DeepSeek-V3",
        "owner": "deepseek-ai",
        "description": "Next generation language model from DeepSeek AI",
        "html_url": "https://github.com/deepseek-ai/DeepSeek-V3",
        "stargazers_count": 101602,
        "forks_count": 16516,
        "open_issues_count": 0,
        "language": "Python",
        "license": None,
        "topics": ["ai", "llm", "deep-learning"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "deepseek-ai/Janus",
        "full_name": "deepseek-ai/Janus",
        "name": "Janus",
        "owner": "deepseek-ai",
        "description": "Janus-Series: Unified Multimodal Understanding and Generation Models",
        "html_url": "https://github.com/deepseek-ai/Janus",
        "stargazers_count": 17705,
        "forks_count": 2236,
        "open_issues_count": 0,
        "language": "Python",
        "license": None,
        "topics": ["multimodal", "image-generation", "ai"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "langgenius/dify",
        "full_name": "langgenius/dify",
        "name": "dify",
        "owner": "langgenius",
        "description": "Production-ready platform for agentic workflow development",
        "html_url": "https://github.com/langgenius/dify",
        "stargazers_count": 129738,
        "forks_count": 20190,
        "open_issues_count": 0,
        "language": "TypeScript",
        "license": "Apache-2.0",
        "topics": ["agent", "workflow", "ai", "llm"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "hacksider/Deep-Live-Cam",
        "full_name": "hacksider/Deep-Live-Cam",
        "name": "Deep-Live-Cam",
        "owner": "hacksider",
        "description": "Real time face swap and one-click video deepfake with only a single image",
        "html_url": "https://github.com/hacksider/Deep-Live-Cam",
        "stargazers_count": 79529,
        "forks_count": 11592,
        "open_issues_count": 0,
        "language": "Python",
        "license": None,
        "topics": ["face-swap", "deepfake", "video"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "openclaw/openclaw",
        "full_name": "openclaw/openclaw",
        "name": "openclaw",
        "owner": "openclaw",
        "description": "Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞",
        "html_url": "https://github.com/openclaw/openclaw",
        "stargazers_count": 205157,
        "forks_count": 37358,
        "open_issues_count": 0,
        "language": "TypeScript",
        "license": None,
        "topics": ["ai", "agent", "assistant"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "block/goose",
        "full_name": "block/goose",
        "name": "goose",
        "owner": "block",
        "description": "An open source, extensible AI agent that goes beyond code suggestions - install, execute, edit, and test with any LLM",
        "html_url": "https://github.com/block/goose",
        "stargazers_count": 30579,
        "forks_count": 2765,
        "open_issues_count": 0,
        "language": "Rust",
        "license": "Apache-2.0",
        "topics": ["agent", "ai", "code", "developer-tools"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "Comfy-Org/ComfyUI",
        "full_name": "Comfy-Org/ComfyUI",
        "name": "ComfyUI",
        "owner": "Comfy-Org",
        "description": "The most powerful and modular diffusion model GUI, api and backend with a graph/nodes interface",
        "html_url": "https://github.com/Comfy-Org/ComfyUI",
        "stargazers_count": 103422,
        "forks_count": 11788,
        "open_issues_count": 0,
        "language": "Python",
        "license": "GPL-3.0",
        "topics": ["stable-diffusion", "image-generation", "diffusion"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "FunAudioLLM/CosyVoice",
        "full_name": "FunAudioLLM/CosyVoice",
        "name": "CosyVoice",
        "owner": "FunAudioLLM",
        "description": "Multi-lingual large voice generation model, providing inference, training and deployment full-stack ability",
        "html_url": "https://github.com/FunAudioLLM/CosyVoice",
        "stargazers_count": 19623,
        "forks_count": 2213,
        "open_issues_count": 0,
        "language": "Python",
        "license": None,
        "topics": ["tts", "text-to-speech", "voice", "speech"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "stanford-oval/storm",
        "full_name": "stanford-oval/storm",
        "name": "storm",
        "owner": "stanford-oval",
        "description": "An LLM-powered knowledge curation system that researches a topic and generates a full-length report with citations",
        "html_url": "https://github.com/stanford-oval/storm",
        "stargazers_count": 27906,
        "forks_count": 2534,
        "open_issues_count": 0,
        "language": "Python",
        "license": None,
        "topics": ["agent", "research", "ai", "llm"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "ItzCrazyKns/Perplexica",
        "full_name": "ItzCrazyKns/Perplexica",
        "name": "Perplexica",
        "owner": "ItzCrazyKns",
        "description": "Perplexica is an AI-powered answering engine",
        "html_url": "https://github.com/ItzCrazyKns/Perplexica",
        "stargazers_count": 28957,
        "forks_count": 3070,
        "open_issues_count": 0,
        "language": "TypeScript",
        "license": None,
        "topics": ["ai", "search", "llm"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "OpenBMB/MiniCPM-o",
        "full_name": "OpenBMB/MiniCPM-o",
        "name": "MiniCPM-o",
        "owner": "OpenBMB",
        "description": "A Gemini 2.5 Flash Level MLLM for Vision, Speech, and Full-Duplex Multimodal Live Streaming on Your Phone",
        "html_url": "https://github.com/OpenBMB/MiniCPM-o",
        "stargazers_count": 23832,
        "forks_count": 1833,
        "open_issues_count": 0,
        "language": "Python",
        "license": "Apache-2.0",
        "topics": ["multimodal", "llm", "vision", "speech"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "LostRuins/koboldcpp",
        "full_name": "LostRuins/koboldcpp",
        "name": "koboldcpp",
        "owner": "LostRuins",
        "description": "Run GGUF models easily with a KoboldAI UI. One File. Zero Install",
        "html_url": "https://github.com/LostRuins/koboldcpp",
        "stargazers_count": 9501,
        "forks_count": 615,
        "open_issues_count": 0,
        "language": "C++",
        "license": None,
        "topics": ["llm", "gguf", "ai"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
    {
        "repo": "QwenLM/Qwen3-VL",
        "full_name": "QwenLM/Qwen3-VL",
        "name": "Qwen3-VL",
        "owner": "QwenLM",
        "description": "Qwen3-VL is the multimodal large language model series developed by Qwen team, Alibaba Cloud",
        "html_url": "https://github.com/QwenLM/Qwen3-VL",
        "stargazers_count": 18311,
        "forks_count": 1597,
        "open_issues_count": 0,
        "language": "Jupyter Notebook",
        "license": None,
        "topics": ["multimodal", "llm", "vision"],
        "category": None,
        "sub_category": None,
        "added_at": time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()),
    },
]

# Load existing repos
with open('repos.json', 'r', encoding='utf-8') as f:
    existing_repos = json.load(f)

# Create a set of existing repo names for quick lookup
existing_names = {repo['full_name'] for repo in existing_repos}

# Add new repos that don't already exist
added_count = 0
for repo in manual_repos:
    if repo['full_name'] not in existing_names:
        existing_repos.append(repo)
        added_count += 1
        print(f"Added: {repo['full_name']}")

# Save updated repos
with open('repos.json', 'w', encoding='utf-8') as f:
    json.dump(existing_repos, f, indent=4)

print(f"\nTotal repos added: {added_count}")
print(f"Total repos in list: {len(existing_repos)}")
